In [ ]:
import pandas as pd
df=pd.read_csv("Titanic-Dataset.csv")

In [ ]:
print("\n500 rows")
df.head(891)

500 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
print("\nDataset Info")
print(df.info())

print("\nDataset Shape")
print(df.shape)

Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Dataset Shape
(891, 12)

In [ ]:
# Data Quality Report (Before Cleaning)

print("\nBEFORE CLEANING")
print("total Rows",len(df))

print("total missing values")
df.isnull().sum()

BEFORE CLEANING
total Rows 891
total missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
print("Duplicate Values:")
df.duplicated().sum()

Duplicate Values:

np.int64(0)

In [ ]:
#Standarized Column Names
df.columns = df.columns.str.strip()

In [ ]:
# Handle Missing Values
# Fill Age with Median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill Embarked with Mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Fill Cabin with "Unknown"
df["Cabin"] = df["Cabin"].fillna("Unknown")

In [ ]:
print("total missing values")
df.isnull().sum()

total missing values

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
# Data Quality Report (After Cleaning)
# -----------------------------
print("\n========== AFTER CLEANING ==========")

print("Total Rows :", len(df))

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

# -----------------------------
# Generate Automated Cleaning Report
# -----------------------------
report = f"""
DATA CLEANING REPORT

Total Records : {len(df)}

Missing Values

{df.isnull().sum()}

Duplicate Records : {df.duplicated().sum()}

Cleaning Completed Successfully.
"""

with open("Cleaning_Report.txt", "w") as file:
    file.write(report)

print("\nCleaning Report Generated Successfully")

# -----------------------------
# Export Cleaned Dataset
# -----------------------------
df.to_csv("Titanic_Cleaned.csv", index=False)

print("Cleaned Dataset Saved Successfully!")

========== AFTER CLEANING ==========
Total Rows : 891

Missing Values
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate Rows : 0

Cleaning Report Generated Successfully
Cleaned Dataset Saved Successfully!